### PR TITLE
268 board game geek thumbnail

### PR DESCRIPTION
**Pull request by jakejgordon**
Creating the pull request  even though it's not quite ready. It's easier to comment at the pull request level (in my opinion)

### CODE REVIEW

**Comment by jakejgordon** [comment]
Overall the code looks great. 

Without having looked at it too closely, if looks like you picked a BGG client and then wrote integration tests for the whole client -- not just the parts that we are using for now? Is this correct? If so, then I guess we are positioned nicely to take advantage of some of the other features. For example, I'd like to see if the BGG game weight is exposed in their API so I can factor that into the NemePoints calculation.

**Comment by vfportero** [comment]
Hi!

This is the first aproach to show you some code and result. I have to change the UI for do it responsive and great!

I'm agree with Jake, we can change a lot the mobile view rendering all the stats in the same td under the name, i'll work on it!

About the new API... I take this project (https://github.com/ervwalter/bgg-json) as origin but I removed a lot of code and refactor it aswell for left only the search and gamedetails calls.

For this two methods i make all the unit and integration tests (and reused other parts as jake's sort method for search).
With this new API we can access to more data (images, categories, mechanics, ratings, polls, expansions, etc...) and we use the current version (the old api was obsoleted for BGG).
Maybe it's interesting to add expansions functionallity when you record a play (indicate if there are any expansion) or show categories as labels in the gamedefinition details view.

About the game weight: yes, it is in the API but i don't getting right now. In the next commit I added to the GameDetails results :)

**Comment by vfportero** [comment]
I'm triying something different is this commit (as usual, not is the final version, it's just to share with you :) )

This is the desktop view (quite similar to the latest one):
captura

And this form mobile:
captura1

I'm using the css hack "flip-scroll"(http://elvery.net/demo/responsive-tables/#flip-scroll) to invert the axes and show always the header at the left and the content at the right with scroll.

This version doesn't solve the problem of the only show a few items in mobile but i think it's better scroll than the bootstrap's thats hides the headers.

I recommend you to pull the code and test it to see the effect.

The other option is to try to fit all data in two columns (Image | Name<br/>Plays<br/>Champion) but this may be too much.

**Comment by jakejgordon** [comment]
I did some playing around and I do think I like this better. I don't have a good way of testing this with an actual touch device to see how well the horizontal scrolling works -- but assuming that isn't too bad then I think this is a solid design. Personally I'd rather scroll vertically on a mobile device but I can't really think of a design that would make this work.

One thing I noticed is that the styling is a little messed up when there is no BGG linkage and hence no image. See the screenshot below:

no_bgg_image

This is going to be a nice enhancement. Keep up the good work!! :+1:

**Comment by jakejgordon** [comment]
I just made this commit to get the partial mock of the GameDefinitionController working again. I didn't fix the unit tests, but was just trying to give you a little help in case you had issues here. If this conflicts with any pending changes you have then feel free to revert this commit: https://github.com/NemeStats/NemeStats/commit/acfd9911e6bbdbe48c02f062120f5324638e4192 @vfportero

**Comment by vfportero** [comment]
Nice Jake! I've already fixed the broken tests and added the exact match query in bgg search (although isn't used right now).I think that Tosho has to add the BoardGameGeek ApiClient.Tests to AppVeyor to achieve full continuous integration with the branch:

Also I've fixed the UI glitch when there are not images.

About the horizontal scroll in mobile, I think that it's good to apply to all tables because makes the tables shorten to reach the table you want to see easily whitout data loss.
If you like this option I can try to apply flipscroll to other tables too and see how it works,

PS: For more accurated mobile tests in desktop you can use the Google Developer Tools (https://developer.chrome.com/devtools/docs/device-mode). 
F12, click to "Toggle Device mode", select your device (iphone 5) and refresh. Then your mouse pointer acts like a finger :smile:

**Comment by vfportero** [comment]
Improved, in the last commit, the create gamedefinition game experience reloading the entire tabla from the server instead add a hardcoded <tr>.

I have to check it out the GameDefinition Details view with the new image to leave this branch ready to merge!

**Comment by jakejgordon** [comment]
Awesome! Will check it out.

Didn't realize Google Developer Tools had this -- will also check that out. Thanks.

In regards to flipping all of the tables, I would be down for trying it out to see how it works. I would definitely do that as a separate feature so we can remain agile and get this one out :+1:

**Comment by jakejgordon** [comment]
Oh yeah, as a separate feature perhaps, a nice touch would be to add the BGG image to the Game Definition details page and the Played Game details page. Also, if you want me to write a batch job to go through and update existing Game Definitions I could do that pretty easily -- especially if you can query on BGG object Id. Just let me know.

**Comment by jakejgordon** [comment]
One other minor idea. It looks like the column will expand to accommodate the full width of the Game Definition name -- which can be pretty long in some cases. It also looks like we could take advantage of some extra vertical space and perhaps let the Game Definition name wrap? Then we could get a more consistent size to the columns? Just and idea and I'll trust your judgment.

Here is a screenshot of iPhone 4 to illustrate:

more_verticle_space

**Comment by vfportero** [comment]
Yes, please, create the job to update current game images :)

**Comment by vfportero** [comment]
Ok, i'm think it's ready! I updated the UI of Player's games and GameDefinition detail,

It's quite simple but, as a first iteration, i think is nice :grinning:

**Comment by jakejgordon** [comment]
Great! Will check it out later.

**Comment by jakejgordon** [comment]
@vfportero Did you make the change so the Game Definition name would wrap? I'm still seeing the below:

wide_game_definition_names

I'll start working on the job to update existing game definitions. Another thing you could check out is on the Game Definition edit page, if you change the Game Definition it doesn't look as though it sets/updates the BGG thumbnail. Is that something you can take care of or should I?

Great work, can't wait to release this feature!

**Comment by jakejgordon** [comment]
Also still seeing 60 retries on the ApiDownloaderService. We should probably do 2 at the most -- considering there is a 15 second timeout.

**Comment by jakejgordon** [comment]
Actually... let me update the code to set a thumbnail when a Game Definition is being edited. This code has some technical debt which I'd like to clean up. Will try to get this done by the end of tomorrow if I can.

**Comment by jakejgordon** [comment]
Another thing I discovered is that BGG has a pretty strict rate limit. We may have to add retry logic after 1s or something like that.

**Comment by vfportero** [comment]
Right! I totally forgotten to delete this retry policy. Maybe, for this version, we can leave without retry (only one try) and add another issue for implement better a retry policy like transient fault handling.

For the text wrap, leave a minutes and i fix it for you :p 

The update GameDefintion with thumbnail addin it's a great improvement, thanks!

**Pull request merged**
