### PR TITLE
343 import bgg games

### PR DESCRIPTION
**Pull request by vfportero**
Changed the GamingGroup UI moving the action button from panel headers to a well inside the panel (i have not moved the "search" button yet... i need to think about this feature before):

screencapture-localhost-44300-gaminggroup-1455297961216

Also i added a badge to count all the panel elements

When you don't have BGG User (the normal status... nobody have bgg setted today) the button says "Configure BGG user to import your games".
When you click the same form on Account.Manage is shown:

configure

Once configured you can import your games with only one click:

imported

### CODE REVIEW

**Comment by jakejgordon** [comment]
I think it looks great! Here are some random ideas/questions, but i don't think anything should hold us up from deploying this:
* I haven't checked lately, but I'm guessing there are still a lot of games that aren't linked to BGG because of typos, people clicking away from the auto-complete, etc. when adding games. Do you think we should do a 1-time cleanup of existing unlinked games (e.g. just manually fix a bunch of them)? My biggest concern would be if people have existing unlinked games, then they do the BGG imports and create duplicates. Right now there would be no way to merge the records. Then again, maybe this is a really, really small issue.
* Maybe we could log BGG api issues in rollbar just in case their API changes and we don't know about it? It looks like we are squishing the errors (e.g. in BoardGameGeekClient)
* If I'm seeing this correctly, we could just add "averageWeight" to GetGameDetails and then I could do this story, right? : https://waffle.io/nemestats/nemestats/cards/562900a8bfd4850300a16479
* The ImportFromBGG action in GameDefinitionController is pretty fat. Should we push some off that stuff down into BusinessLogic?
* Will test tomorrow!

**Comment by vfportero** [comment]
Yes, we need to do that kind of maintain to avoid duplicates. 
Maybe adding a additional step to create/import games solves the problem (instead of autocomplete you type the game and click "Search". Then results from BGG are displayed and you choose the game to add).
This could be the way to avoid the typos but it's other issue definitely.

Anyway. the main purpose of this feature is to fill with games an empty gaminggroup at their creation. The use of this feature after creating will be residual, in my opinion.

About the logging, i'm agree. I don't know how rollbar works but i will implement asap :)

Yes, the controller has too much logic. Where is the correct place for this kind of stuff? GameDefinitionSaver?

At least, i've added the AverageWeight to GetGameDetails query :dancer:

**Comment by jakejgordon** [comment]
* For Rollbar, just see RollbarExceptionFilter for example of logging an error
* For thinning out the one controller action, maybe just create an IBoardGameGeekImporter or something. No need to add it to the bloated GameDefinitionSaver :)

Anyway, I trust your judgment on when to deploy. You could either make these 2 changes or just deploy now -- up to you!

**Comment by vfportero** [comment]
Ok. done both things :)

I will merge when tests pass

**Pull request merged**
