### PR TITLE
Cascading player delete including achievements, champions, and nemesis.

### PR DESCRIPTION
**Pull request by kleric42**
I do believe this covers all the places with a playerId's FK for deletion purposes.

Please check my work though. :)

### CODE REVIEW

**Comment by jewelker** [comment]
Thanks for the hard work!

Unfortunately I have just tested this morning and received more "Oh Crap!" errors. (Thanks for the clean Oh Crap! message, btw)   I was trying to delete Carolyn and Karen W. from our Katy King Maker's Board Game Group. I think these are players 20477 and 20478 (if the URL is any indication).

**Comment by kleric42** [comment]
Hi jewelker, I don't believe the code has been pushed to the site yet!

**Comment by jakejgordon** [comment]
I just pushed it. Give it a shot now!

**Comment by jewelker** [comment]
Ah! I WANT this to work so much!  I tried deleting all of our inactive usernames and got the same "Oh Crap" error each time.  If it helps, the inactive users are:
Jared P - 20473
cgardner13b - 20474
Jared C - 20476
Carolyn - 20477
Karen W - 20478
 
I also tried to delete one from the Welker Family Gaming Group and that had the same error:
DELETEKaren W. - 20483

**Comment by jakejgordon** [comment]
Hey jewelker can you try again? I just pulled down the production database
and simulated being an admin in your gaming group and it successfully
deleted. Could you try again and if it blows up can you give me the exact
time of the failure and I'll look in the logs?

Sorry this has been such a pain! It was a little tougher than one might
think to totally purge the DB of all traces of a Player :P

**Comment by jewelker** [comment]
It works, it works!! At least twice.   
I deleted 2 of the problem records. I got "Oh Crap" three times: 
Jared C., player 20476
Carolyn, player 20477
cgardner13b, player 20474

**Pull request merged**
